root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  entrypoint = "./tmp/api"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500
  kill_delay = "200ms"
  rerun = false
  rerun_delay = 500
  send_interrupt = true

[log]
  time = false
  main_only = false

[color]
  main     = "magenta"
  watcher  = "cyan"
  build    = "yellow"
  runner   = "green"

[misc]
  clean_on_exit = true
